In [49]:
#https://www.brilliantcode.net/1022/numpy-tutorial-basics-array-creations/?cli_action=1622963967.244
import numpy as np

In [ ]:
#NumPy中的陣列和Python內建的陣列有什麼不同呢？
'''
NumPy的array是NumPy中名為ndarray的Class所定義的，
而這個array當然支援多維度陣列，也可以說它是一個支援矩陣(Martix)的類別
然而，Python的array則是標準函式庫內建的類別
而Python的array能支援單維度(1維)的陣列，而且提供的功能選項也比NumPy來得少
'''

#ndarray 重要屬性
'''
ndarray.ndim：NumPy ndarray物件的維度
ndarry.shape：ndarry物件的每一個維度的大小(size)，回傳資料類別為Tuple
ndarry.size：ndarry物件所組成之array的總元素數量，回應之數值會等於ndarray.shape的每個元素相乘
ndarry.dtype：ndarray物件內組成元素的型態
ndarray.itemsize：陣列中每一個元素的大小(Bytes) (ex: int64, itemsize = 64/8 = 8 Bytes)
ndarry.data：這是一個存有實際陣列元素的緩衝，通常我們不需要使用這個屬性，因為我們可以使用index存取這些元素。
'''

In [14]:
a = np.array([1, 2, 3, 4, 5])
print(a, a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.data)

[1 2 3 4 5] 1 (5,) 5 int64 8 <memory at 0x7f8793a53ac0>


In [13]:
a = np.array([1.25, 2.25, 3.25, 4.25, 5.25])
print(a, a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.data)

[1.25 2.25 3.25 4.25 5.25] 1 (5,) 5 float64 8 <memory at 0x7f8793a53400>


In [15]:
aa = np.array([(1.9, 1.5, 1.3), (2.9, 2.5, 2.3)], dtype=np.int16)
# ndarray.ndim
print("ndim:{0}".format(aa.ndim))
# ndarry.shape
print("shape:{0}".format(aa.shape))
# ndarry.size
print("size:{0}".format(aa.size))
# ndarry.dtype
print("dtype:{0}".format(aa.dtype))
# ndarray.itemsize
print("itemsize:{0}".format(aa.itemsize))
# ndarry.data
print("data:{0}".format(aa.data))

ndim:2
shape:(2, 3)
size:6
dtype:int16
itemsize:2
data:<memory at 0x7f8793a116c0>


In [26]:
## 1維陣列
'''
1維陣列
np.array( [<陣列元素用逗號隔開>] )：簡易一維陣列
np.arange( 起始值, 結束值, 步幅, 資料型別 )：也是產生一維陣列，
和np.array()的差別在於arange擁有較大的彈性，而且元素數值是自動化產生！
'''
a = np.array([6, 5, 4, 3, 2])
print("a={0}".format(a))
b = np.arange(10)
print("b={0}".format(b))
c = np.arange(0, 10, 1.5, dtype=np.float64)
c

a=[6 5 4 3 2]
b=[0 1 2 3 4 5 6 7 8 9]


array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [23]:
##2維陣列
'''
np.array( [[<Row1陣列元素>], [<Row2陣列元素>]] )：產生簡易二維陣列
'''
## 2維陣列 2-by-3 array
b = np.array([[1.1, 1.2, 1.3], [2.1, 2.2, 2.3]])
b

array([[1.1, 1.2, 1.3],
       [2.1, 2.2, 2.3]])

In [27]:
## Assign a particular data type to an array
aa = np.array([[1.9, 1.5, 1.3], [2.9, 2.5, 2.3]], dtype=np.int16)
aa

array([[1, 1, 1],
       [2, 2, 2]], dtype=int16)

In [ ]:
# zeros, ones, empty, arange, linspace

In [34]:
#np.zeros( (陣列各維度大小用逗號區分) )：建立全為0的陣列，可以小括號定義陣列的各個維度的大小！
zeros = np.zeros( (3, 5) )
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
#np.ones( (陣列各維度大小用逗號區分) )：用法與np.zeros一樣！
ones = np.ones( (3, 5) )
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
#np.empty( (陣列各維度大小用逗號區分) )：用法與np.zeros一樣，但唯一的差別是NumPy不會初始化陣列內元素的初始值，
#所以內容將會是不確定的
e = np.empty( (2, 5) )
e

array([[0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323, 3.5e-323, 4.0e-323, 4.4e-323]])

In [46]:
#np.arange( 起始值, 結束值, 步幅, 資料型別 )：也是產生一維陣列，和np.array()的差別在於arange擁有較大的彈性，
#而且元素數值是自動化產生！步幅決定每隔多少數值產生一個元素(等差的概念)。
r1 = np.arange(15, 30, 5)
r1

array([15, 20, 25])

In [48]:
#np.linspace( 起始值, 結束值, 起始與結束的區間內要產生幾個元素 )：這個在畫線時還蠻常用到的！只要給定陣列的區間(起始值、結束值)，就可以要求在這個區間內產生幾個元素！
lin = np.linspace(15, 30, 3)
lin

array([15. , 22.5, 30. ])