In [2]:
# NumPy 廣播機制
#https://ithelp.ithome.com.tw/articles/10195830
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([2,2,2])

In [4]:
a*b

array([2, 4, 6])

In [5]:
c = np.array([1.0, 2.0, 3.0])
d = 2
c * d

array([2., 4., 6.])

In [8]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [9]:
x2 = x.reshape(4,1)
x2

array([[0],
       [1],
       [2],
       [3]])

In [11]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [12]:
x2 + y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [15]:
#https://openhome.cc/Gossip/DCHardWay/Broadcasting.html
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1])

In [17]:
a + b

array([[2, 3, 4],
       [5, 6, 7]])

In [18]:
c = np.array([[7, 8, 9]]) 

In [19]:
a + c

array([[ 8, 10, 12],
       [11, 13, 15]])

In [21]:
d = np.array([[7], [8], [9]]) 
d

array([[7],
       [8],
       [9]])

In [22]:
#ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 
a + d 

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 