In [1]:
#https://www.brilliantcode.net/1111/numpy-tutorial-shape-manipulation-stack-split-matrices/
import numpy as np

In [3]:
#np.reshape(a, b)：這是最基本的塑形功能，可以直接將陣列重新塑形成a-by-b或是更高維度的形狀！
a = np.arange(1, 51).reshape(5, 10)
print("a.shape:",format(a.shape))
a

a.shape: (5, 10)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [4]:
#np.reshape(a, b, -1)：使用-1，代表這個維度就交給NumPy自動計算！
a = np.arange(1, 51).reshape(5, 10)
print("a.reshape(5, 2, 5)=>\n{0}".format(a.reshape(5, 2, 5)))
 
print()
#效果會跟.reshape(5, 2, 5)是一樣的，因為NumPy算得出來！
print("a.reshape(5, 2, -1)=>\n{0}".format(a.reshape(5, 2, -1)))

a.reshape(5, 2, 5)=>
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]]]

a.reshape(5, 2, -1)=>
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]]]


In [15]:
#np.ravel()：此功能會回傳一個將陣列或矩陣經扁平化(flattened)處理後的陣列
a = np.arange(1, 51).reshape(5, 5, 2)
print("a=> \n{0}".format(a))
print("a.ravel()=>\n {0}".format(a.ravel()))

a=> 
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]

 [[21 22]
  [23 24]
  [25 26]
  [27 28]
  [29 30]]

 [[31 32]
  [33 34]
  [35 36]
  [37 38]
  [39 40]]

 [[41 42]
  [43 44]
  [45 46]
  [47 48]
  [49 50]]]
a.ravel()=>
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [16]:
b = np.arange(1, 7).reshape(2, 3)
print("b =>\n{0}".format(b))
 
print()
print("轉置矩陣b(Transpose b.)\n=>\n{0}".format(b.T))

b =>
[[1 2 3]
 [4 5 6]]

轉置矩陣b(Transpose b.)
=>
[[1 4]
 [2 5]
 [3 6]]


In [17]:
'''
np.vstack(a, b)：將a, b矩陣沿著垂直軸堆疊！
np.hstack(a, b)：將a, b矩陣沿著水平軸堆疊！
'''
a = np.arange(1,11).reshape(2,5)
print("a=>\n{0}".format(a))
 
print()
# 水平堆疊
print("np.vstack((a,a))=>\n{0}".format(np.hstack((a,a))))
 
print()
# 垂直堆疊
print("np.hstack((a,a))=>\n{0}".format(np.vstack((a,a))))

a=>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

np.vstack((a,a))=>
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]]

np.hstack((a,a))=>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
a = np.round(np.arange(1, 13).reshape(2, 6)*10, 0)
print("a=>\n{0}".format(a))
 
print()
print("----hsplit----")
output1 = np.hsplit(a, 2)
i = 0
for smallMatrix in output1:
    print("np.hsplit(a, 3) [{0}]=>\n{1}".format(i, smallMatrix))
    i+=1
 
print("Type of output1: {0}".format(type(output1)))
newOutput1 = np.array(output1)
print("Shape of output1: {0}".format(newOutput1.shape))
 
print()
print("----vsplit----")
output2 = np.vsplit(a, 2)
i = 0
for smallMatrix in output2:
    print("np.vsplit(a, 2) [{0}]=>{1}".format(i, smallMatrix))
    i+=1
print()
print("Type of output2: {0}".format(type(output2)))
newOutput2 = np.array(output2)
print("Shape of output2: {0}".format(newOutput2.shape))

a=>
[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]

----hsplit----
np.hsplit(a, 3) [0]=>
[[10 20 30]
 [70 80 90]]
np.hsplit(a, 3) [1]=>
[[ 40  50  60]
 [100 110 120]]
Type of output1: <class 'list'>
Shape of output1: (2, 2, 3)

----vsplit----
np.vsplit(a, 2) [0]=>[[10 20 30 40 50 60]]
np.vsplit(a, 2) [1]=>[[ 70  80  90 100 110 120]]

Type of output2: <class 'list'>
Shape of output2: (2, 1, 6)
