In [1]:
#https://www.brilliantcode.net/1062/numpy-tutorial-basic-operations/
import numpy as np

In [2]:
print('維度相同的矩陣相加、減:')
# 維度相同的矩陣相加、減
a = np.array( [6, 7, 8, 9] )
b = np.arange( 4 )
c = a - b
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("c=>{0}".format(c))
 
 
print('\n同加、同減一個數值:')
# 同加、同減一個數值
a += 5
print("a=>{0}".format(a))
b -= 5
print("b=>{0}".format(b))
 
 
print('\n次方：')
# d是b的2次方
# d is squared of b.
d = b**2
print("d=>{0}".format(d))

維度相同的矩陣相加、減:
a=>[6 7 8 9]
b=>[0 1 2 3]
c=>[6 6 6 6]

同加、同減一個數值:
a=>[11 12 13 14]
b=>[-5 -4 -3 -2]

次方：
d=>[25 16  9  4]


In [4]:
a = np.arange(5)
b = np.arange(10, 5, -1)
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("\n同除2:")
# c等於a同除以2
c = a / 2
print("c=>{0}".format(c))
 
print("\n同乘2:")
# d等於b同乘以2
d = b * 2
print("d=>{0}".format(d))

a=>[0 1 2 3 4]
b=>[10  9  8  7  6]

同除2:
c=>[0.  0.5 1.  1.5 2. ]

同乘2:
d=>[20 18 16 14 12]


In [5]:
# 矩陣相乘
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A, B相乘(矩陣乘法) =>\n{0}".format(A.dot(B)))
print()
print("A, B相對應位置相乘=>\n{0}".format(A*B))

A, B相乘(矩陣乘法) =>
[[19 22]
 [43 50]]

A, B相對應位置相乘=>
[[ 5 12]
 [21 32]]


In [9]:
# 印出陣列中小於等於0的元素
e = np.array([5, -1, 3, 9, 0])
print("陣列e裡面哪幾個位置的元素值小於等於零?:{0}".format(e<=0))
 
# 把小於等於0的元素取代成99
e[e<=0] = 99
print("把小於等於0的元素取代成99=>{0}".format(e))

陣列e裡面哪幾個位置的元素值小於等於零?:[False  True False False  True]
把小於等於0的元素取代成99=>[ 5 99  3  9 99]


In [14]:
#常犯錯誤, 兩個要做運算的陣列型別根本不符
## Operations: += *=
a = np.ones((2, 3), dtype='int') #change to 'float' to correct the exception
b = np.random.random( (2,3) ) #float
a *= 5
print("a=>\n{0}".format(a))
b += a
print("b=>\n{0}".format(b))
 
a += b
print("a=>\n{0}".format(a))

a=>
[[5 5 5]
 [5 5 5]]
b=>
[[5.34952516 5.06274111 5.28364041]
 [5.33894883 5.07091964 5.7444525 ]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [16]:
## Methods: sum, min, max, mean
a = np.random.random((3, 3))
print("sum => {0}\nmax => {1}\nmin => {2}\nmean => {3}".format(a.sum(), a.max(), a.min(), a.mean()))

sum => 3.337870662145246
max => 0.787721924573739
min => 0.10501661922893468
mean => 0.3708745180161384


In [21]:
b = np.arange(12).reshape(2, 6)
print("b=>\n{0}".format(b))
 
print()
# 加總每一欄(column)
print("b.sum(axis=0)=>{0}".format(b.sum(axis=0)))
 
print()
# 加總每一列(row)
print("b.sum(axis=1)=>{0}".format(b.sum(axis=1)))
 
print()
revenu = np.round(np.random.random((1,12)) * 100, 0)
print("revenu=>\n{0}".format(revenu))
 
print()
# 累計加總(每一項數值等於自己加上前一項)
print("Cumulative Sum of revenu=>\n{0}".format(revenu.cumsum()))

b=>
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

b.sum(axis=0)=>[ 6  8 10 12 14 16]

b.sum(axis=1)=>[15 51]

revenu=>
[[ 76.  34.  40.  46.  62.  46.  72.  12.  57. 100.  23.   5.]]

Cumulative Sum of revenu=>
[ 76. 110. 150. 196. 258. 304. 376. 388. 445. 545. 568. 573.]


In [22]:
B = np.arange(3)
B_exp = np.exp(B)
print("B_exp=> {0}".format(B_exp))
 
B_sqrt = np.sqrt(B)
print("B_sqrt=> {0}".format(B_sqrt))
 
C = np.array([2, 1, 0])
print("np.add(B, C)=> {0}".format(np.add(B, C)))

B_exp=> [1.         2.71828183 7.3890561 ]
B_sqrt=> [0.         1.         1.41421356]
np.add(B, C)=> [2 2 2]
