In [8]:
#http://changtw-blog.logdown.com/posts/895468-python-numpy-axis-concept-organize-notes

In [2]:
import numpy as np

In [3]:
# 1維
ndarray = np.arange(1,10)
ndarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 2維
ndarray = ndarray.reshape(3,3)
ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
ndarray[:2,1:]

array([[2, 3],
       [5, 6]])

In [6]:
# 3維
c = np.arange(24).reshape(2,4,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])