In [1]:
#https://www.brilliantcode.net/1093/numpy-1-14-tutorial-04-indexing-slicing-iterating-from-function/
import numpy as np

In [5]:
'''
索引(Indexing)的用途不外乎就是為了要從陣列和矩陣中取值，但除此之外有很多種功能！
可以取出連續區間，還可以間隔取值！

選取連續區間 [a:b], 不含b
'''

a = np.arange(10) ** 2
print("a=> {0}".format(a))
print()
print("a[2:5]=> {0}".format(a[2:5]))

a=> [ 0  1  4  9 16 25 36 49 64 81]

a[2:5]=> [ 4  9 16]


In [9]:
'''
以1維陣列來說明x[a:b:c]
a：選取資料的起始索引
b：選取資料的結束索引+1
c：選取資料間隔，以索引值可以被此值整除的元素，不指定表示1
'''
a = np.arange(10) ** 2
a[3:8:4] = -1
print("a[3:8:4]=> {0}".format(a))

a[3:8:4]=> [ 0  1  4 -1 16 25 36 -1 64 81]


In [13]:
'''
倒序[::-1]
'''
a = np.arange(10) ** 2
print("a[:,:,-1])=> {0}".format(a[::-1]))
print("a[:,:,-2])=> {0}".format(a[::-2]))

a[:,:,-1])=> [81 64 49 36 25 16  9  4  1  0]
a[:,:,-2])=> [81 49 25  9  1]


In [14]:
# Iteracted over
a = np.arange(10) ** 2
for i in a:
    print("a**(1/2)=> {0}".format(np.round(i**(1/2), 0)))

a**(1/2)=> 0.0
a**(1/2)=> 1.0
a**(1/2)=> 2.0
a**(1/2)=> 3.0
a**(1/2)=> 4.0
a**(1/2)=> 5.0
a**(1/2)=> 6.0
a**(1/2)=> 7.0
a**(1/2)=> 8.0
a**(1/2)=> 9.0


In [16]:
#直接將矩陣內所有元素扁平化，依序取出所有元素！此功能必須搭配for-loop, while-loop使用！
#扁平化(.flat)會變成一維陣列！
b = np.arange(1, 13).reshape(3, 4)
for element in b.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12


In [18]:
#np.fromfunction(函數名稱, 形狀, 資料型別)
def my_f(row, col):
    return row*5 + col
 
b = np.fromfunction(my_f, (5, 5), dtype=int)
print(b)
 
print()
print(b[0:5, 4])
 
print()
print(b[:, 4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[ 4  9 14 19 24]

[ 4  9 14 19 24]
